# 2.22: Lab: Linear & Polynomial Regresssion

## Linear regression and Stochastic Gradient Descent

1.

Load the dataset:
Load the diabetes data https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html


In [4]:
from sklearn import datasets
diabetes = datasets.load_diabetes()

diabetes['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [ ]:
X = diabetes['data']
y = diabetes['target']

2.

Build two linear models:

- A Linear Regression model: from sklearn.linear_model import LinearRegression
- A Stochastic Gradient Descent regression model: from sklearn.linear_model import SGDRegressor (Take a look at the book for an illustration of how to parameterise this)


### Linear regression

In [7]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()

### Stochastic Gradient Descent

In [8]:
from sklearn.linear_model import SGDRegressor
sgd_model = SGDRegressor()

3.

Fit both of these to the diabetes dataset and compare their performance in terms of their score. Also look at the coefficients and the intercept values and the RMSE.

In [9]:
# Fit both models
lr_model.fit(X, y)
sgd_model.fit(X, y)

# Compare score, coefficients, intercept, and RMSE
from sklearn.metrics import mean_squared_error
import numpy as np

lr_pred = lr_model.predict(X)
sgd_pred = sgd_model.predict(X)

results = {
    "LinearRegression": {
        "score": lr_model.score(X, y),
        "coefficients": lr_model.coef_,
        "intercept": lr_model.intercept_,
        "rmse": np.sqrt(mean_squared_error(y, lr_pred)),
    },
    "SGDRegressor": {
        "score": sgd_model.score(X, y),
        "coefficients": sgd_model.coef_,
        "intercept": sgd_model.intercept_,
        "rmse": np.sqrt(mean_squared_error(y, sgd_pred)),
    },
}

for name, metrics in results.items():
    print(f"{name}:")
    print(f"  score: {metrics['score']}")
    print(f"  intercept: {metrics['intercept']}")
    print(f"  rmse: {metrics['rmse']}")
    print(f"  coefficients: {metrics['coefficients']}\n")


LinearRegression:
  score: 0.5177484222203499
  intercept: 152.13348416289597
  rmse: 53.47612876402657
  coefficients: [ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]

SGDRegressor:
  score: 0.43675815368864235
  intercept: [152.14084759]
  rmse: 57.792381139295856
  coefficients: [  47.78181174  -41.46752054  277.03698101  191.66651251   32.89383562
    4.60043794 -155.54782124  137.03964308  243.61201153  132.88361772]



/home/ross/miniconda3/envs/CS830_Study/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:1612: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


## Polynomial Features

1. Create an array of random data and transform this using a 3rd degree polynomial.

In [11]:
np.random.seed(13)   # unlucky for some

m = 100
X_rand = 13 * np.random.rand(m, 1) - 6.66

from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=3, include_bias=False)
X_poly = poly_features.fit_transform(X_rand)
X_poly

array([[ 3.45013134e+00,  1.19034062e+01,  4.10683149e+01],
       [-3.57196414e+00,  1.27589278e+01, -4.55744326e+01],
       [ 4.05562092e+00,  1.64480611e+01,  6.67071007e+01],
       [ 5.89473957e+00,  3.47479547e+01,  2.04830143e+02],
       [ 5.98381448e+00,  3.58060357e+01,  2.14256675e+02],
       [-7.65159784e-01,  5.85469494e-01, -4.47977712e-01],
       [ 1.25755202e+00,  1.58143707e+00,  1.98873938e+00],
       [ 3.42184469e+00,  1.17090211e+01,  4.00664516e+01],
       [ 1.68097348e+00,  2.82567185e+00,  4.74987944e+00],
       [ 2.72623698e+00,  7.43236809e+00,  2.02623968e+01],
       [-6.20452519e+00,  3.84961328e+01, -2.38850225e+02],
       [-2.78015688e+00,  7.72927227e+00, -2.14885895e+01],
       [-5.89933761e+00,  3.48021842e+01, -2.05309834e+02],
       [ 4.48179225e+00,  2.00864618e+01,  9.00233489e+01],
       [-1.81289764e+00,  3.28659784e+00, -5.95826547e+00],
       [ 2.17802337e+00,  4.74378580e+00,  1.03320763e+01],
       [-3.32836066e+00,  1.10779847e+01

2. Create a 2-D array of data and transform this using a 2nd degree polynomial

In [12]:
X_2d = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
    [7.0, 8.0],
])

poly_features_2d = PolynomialFeatures(degree=2, include_bias=False)
X_2d_poly = poly_features_2d.fit_transform(X_2d)

X_2d_poly


array([[ 1.,  2.,  1.,  2.,  4.],
       [ 3.,  4.,  9., 12., 16.],
       [ 5.,  6., 25., 30., 36.],
       [ 7.,  8., 49., 56., 64.]])

4. If you built model on training data using this approach, what would you need to do to the test data?

Train transformer on training data, then use it to transform test data in the same way before prediction.